name: Deploy documentation to Pages
on:
  push:
    branches:
    - publish
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
    - name: Setup python
      uses: actions/setup-python@v5
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build and Deploy
      uses: sphinx-notes/pages@v3
